import { Village, Farmer, VLE, MachineryRequest, TransactionHistoryItem } from './types';

export const INITIAL_VILLAGES: Village[] = [
  {
    id: 'vil-1',
    name: 'Rampur',
    farmersCount: 142,
    waterResources: 'Canal network, 4 Community Tube-wells',
    acresUnderCultivation: 860,
    district: 'Varanasi',
    panchayat: 'Rampur Gram Panchayat',
  },
  {
    id: 'vil-2',
    name: 'Sonapur',
    farmersCount: 98,
    waterResources: 'River basin feeder, 2 Rainwater check-dams',
    acresUnderCultivation: 620,
    district: 'Mirzapur',
    panchayat: 'Sonapur Gram Panchayat',
  },
  {
    id: 'vil-3',
    name: 'Shivnagar',
    farmersCount: 165,
    waterResources: 'Groundwater Borewells, Percolation pond',
    acresUnderCultivation: 1050,
    district: 'Varanasi',
    panchayat: 'Shivnagar Gram Panchayat',
  },
  {
    id: 'vil-4',
    name: 'Dharampur',
    farmersCount: 84,
    waterResources: 'Sub-canal branch, 3 Solar irrigation pumps',
    acresUnderCultivation: 510,
    district: 'Jaunpur',
    panchayat: 'Dharampur Gram Panchayat',
  },
];

export const INITIAL_FARMERS: Farmer[] = [
  {
    id: 'farm-1',
    name: 'Ramesh Patel',
    mobile: '9876543210',
    village: 'Rampur',
    landAcres: 5.5,
    primaryCrop: 'Wheat & Mustard',
    registeredDate: '2025-01-10',
  },
  {
    id: 'farm-2',
    name: 'Sunita Devi',
    mobile: '9812345678',
    village: 'Sonapur',
    landAcres: 3.2,
    primaryCrop: 'Paddy & Pulses',
    registeredDate: '2025-01-22',
  },
  {
    id: 'farm-3',
    name: 'Vikram Singh',
    mobile: '9765432109',
    village: 'Rampur',
    landAcres: 8.0,
    primaryCrop: 'Sugarcane & Wheat',
    registeredDate: '2025-02-04',
  },
  {
    id: 'farm-4',
    name: 'Meena Kumari',
    mobile: '9934567890',
    village: 'Shivnagar',
    landAcres: 4.0,
    primaryCrop: 'Vegetables & Paddy',
    registeredDate: '2025-02-18',
  },
  {
    id: 'farm-5',
    name: 'Suresh Yadav',
    mobile: '9845123456',
    village: 'Dharampur',
    landAcres: 6.5,
    primaryCrop: 'Maize & Wheat',
    registeredDate: '2025-03-01',
  },
];

export const INITIAL_VLES: VLE[] = [
  {
    id: 'vle-1',
    name: 'Rajesh Kumar',
    mobile: '9123456780',
    village: 'Rampur',
    centerName: 'Rampur Kisan Seva Kendra',
    totalFarmersServed: 128,
    machineryStock: [
      {
        id: 'mach-1',
        name: 'Tractor 45HP with Trolley',
        category: 'Land Preparation & Haulage',
        availableUnits: 2,
        totalUnits: 3,
        rateDescription: '₹800 / hour',
      },
      {
        id: 'mach-2',
        name: 'Rotary Tiller (Rotavator)',
        category: 'Soil Tillage',
        availableUnits: 1,
        totalUnits: 2,
        rateDescription: '₹950 / acre',
      },
      {
        id: 'mach-3',
        name: 'Combine Harvester',
        category: 'Harvesting',
        availableUnits: 0, // Out of stock to test disabled/warning behavior!
        totalUnits: 1,
        rateDescription: '₹1,800 / acre',
      },
      {
        id: 'mach-4',
        name: 'Seed-cum-Fertilizer Drill',
        category: 'Sowing',
        availableUnits: 2,
        totalUnits: 2,
        rateDescription: '₹600 / acre',
      },
      {
        id: 'mach-5',
        name: 'Power Sprayer (16L Battery)',
        category: 'Crop Protection',
        availableUnits: 4,
        totalUnits: 4,
        rateDescription: '₹250 / day',
      },
    ],
  },
  {
    id: 'vle-2',
    name: 'Anita Sharma',
    mobile: '9234567891',
    village: 'Sonapur',
    centerName: 'Sonapur Krishi Vikas Kendra',
    totalFarmersServed: 85,
    machineryStock: [
      {
        id: 'mach-1',
        name: 'Tractor 45HP with Trolley',
        category: 'Land Preparation & Haulage',
        availableUnits: 1,
        totalUnits: 2,
        rateDescription: '₹850 / hour',
      },
      {
        id: 'mach-3',
        name: 'Combine Harvester',
        category: 'Harvesting',
        availableUnits: 1,
        totalUnits: 1,
        rateDescription: '₹1,750 / acre',
      },
      {
        id: 'mach-6',
        name: 'Multi-crop Thresher',
        category: 'Post-Harvest',
        availableUnits: 1,
        totalUnits: 1,
        rateDescription: '₹700 / hour',
      },
    ],
  },
  {
    id: 'vle-3',
    name: 'Manoj Verma',
    mobile: '9345678902',
    village: 'Shivnagar',
    centerName: 'Shivnagar Gramin Seva Kendra',
    totalFarmersServed: 140,
    machineryStock: [
      {
        id: 'mach-1',
        name: 'Tractor 45HP with Trolley',
        category: 'Land Preparation & Haulage',
        availableUnits: 2,
        totalUnits: 2,
        rateDescription: '₹800 / hour',
      },
      {
        id: 'mach-2',
        name: 'Rotary Tiller (Rotavator)',
        category: 'Soil Tillage',
        availableUnits: 1,
        totalUnits: 1,
        rateDescription: '₹900 / acre',
      },
      {
        id: 'mach-7',
        name: 'Laser Land Leveler',
        category: 'Land Grading',
        availableUnits: 1,
        totalUnits: 1,
        rateDescription: '₹1,100 / hour',
      },
    ],
  },
];

export const INITIAL_REQUESTS: MachineryRequest[] = [
  {
    id: 'req-101',
    farmerId: 'farm-1',
    farmerName: 'Ramesh Patel',
    farmerVillage: 'Rampur',
    farmerMobile: '9876543210',
    vleId: 'vle-1',
    vleName: 'Rajesh Kumar',
    machineryId: 'mach-1',
    machineryName: 'Tractor 45HP with Trolley',
    requestedDate: '2026-09-20',
    quantityOrArea: '4 Acres',
    requestDate: '2026-09-14',
    notes: 'Need for plowing before rabi sowing.',
    status: 'Pending',
  },
  {
    id: 'req-102',
    farmerId: 'farm-1',
    farmerName: 'Ramesh Patel',
    farmerVillage: 'Rampur',
    farmerMobile: '9876543210',
    vleId: 'vle-1',
    vleName: 'Rajesh Kumar',
    machineryId: 'mach-3',
    machineryName: 'Combine Harvester',
    requestedDate: '2026-09-22',
    quantityOrArea: '5.5 Acres',
    requestDate: '2026-09-15',
    notes: 'Crop is ready for immediate harvesting.',
    status: 'Pending', // Notice: mach-3 is currently 0 available in vle-1, so this lets VLE test the unavailable stock UI!
  },
  {
    id: 'req-103',
    farmerId: 'farm-3',
    farmerName: 'Vikram Singh',
    farmerVillage: 'Rampur',
    farmerMobile: '9765432109',
    vleId: 'vle-1',
    vleName: 'Rajesh Kumar',
    machineryId: 'mach-2',
    machineryName: 'Rotary Tiller (Rotavator)',
    requestedDate: '2026-09-18',
    quantityOrArea: '3 Acres',
    requestDate: '2026-09-12',
    notes: 'Secondary soil pulverization for sugarcane plot.',
    status: 'Accepted',
  },
  {
    id: 'req-104',
    farmerId: 'farm-2',
    farmerName: 'Sunita Devi',
    farmerVillage: 'Sonapur',
    farmerMobile: '9812345678',
    vleId: 'vle-2',
    vleName: 'Anita Sharma',
    machineryId: 'mach-6',
    machineryName: 'Multi-crop Thresher',
    requestedDate: '2026-09-10',
    quantityOrArea: '2 Days',
    requestDate: '2026-09-08',
    notes: 'Pulse crop threshing.',
    status: 'Rejected',
    rejectionReason: 'Already scheduled for another farmer cluster on that date.',
  },
];

export const INITIAL_TRANSACTION_HISTORY: TransactionHistoryItem[] = [
  {
    id: 'tx-201',
    farmerId: 'farm-1',
    farmerName: 'Ramesh Patel',
    vleId: 'vle-1',
    vleName: 'Rajesh Kumar',
    productOrService: 'Tractor Plowing Service (4 hrs)',
    date: '2026-08-15',
    quantity: '4 Hours',
    amount: 3200,
    status: 'Completed',
  },
  {
    id: 'tx-202',
    farmerId: 'farm-1',
    farmerName: 'Ramesh Patel',
    vleId: 'vle-1',
    vleName: 'Rajesh Kumar',
    productOrService: 'Certified Wheat Seed HD-2967',
    date: '2026-08-28',
    quantity: '40 Kg',
    amount: 1450,
    status: 'Delivered',
  },
  {
    id: 'tx-203',
    farmerId: 'farm-1',
    farmerName: 'Ramesh Patel',
    vleId: 'vle-1',
    vleName: 'Rajesh Kumar',
    productOrService: 'Power Sprayer Rental (2 days)',
    date: '2026-09-02',
    quantity: '2 Days',
    amount: 500,
    status: 'Completed',
  },
  {
    id: 'tx-204',
    farmerId: 'farm-3',
    farmerName: 'Vikram Singh',
    vleId: 'vle-1',
    vleName: 'Rajesh Kumar',
    productOrService: 'Rotary Tiller Land Prep',
    date: '2026-09-05',
    quantity: '5 Acres',
    amount: 4750,
    status: 'Completed',
  },
  {
    id: 'tx-205',
    farmerId: 'farm-2',
    farmerName: 'Sunita Devi',
    vleId: 'vle-2',
    vleName: 'Anita Sharma',
    productOrService: 'Soil Health Testing & Analysis',
    date: '2026-08-18',
    quantity: '1 Report',
    amount: 350,
    status: 'Completed',
  },
  {
    id: 'tx-206',
    farmerId: 'farm-4',
    farmerName: 'Meena Kumari',
    vleId: 'vle-3',
    vleName: 'Manoj Verma',
    productOrService: 'Laser Land Leveling Service',
    date: '2026-08-22',
    quantity: '3 Hours',
    amount: 3300,
    status: 'Completed',
  },
];
